name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - numpy=2.2.2
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - matplotlib=3.10.0
  - tqdm=4.67.1
  - docopt=0.6.2
  - notebook=7.3.2
  - pip=25.0
  - tensorboard=2.17.0
  - pip:
    - sentencepiece==0.2.0
    - sacrebleu==2.5.1
    - nltk==3.9.1
    - timeout_decorator==0.5.0
    - "--find-links https://download.pytorch.org/whl/torch"
    - torch==2.6.0; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.6.0+cpu; sys_platform == "linux" or sys_platform == "win32"